# Generated by Django 5.0.1 on 2024-02-13 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuildNestApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
