# Generated by Django 5.0.1 on 2024-02-19 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuildNestApp', '0004_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructionsite',
            name='site_name',
        ),
    ]
