# Generated by Django 5.0.1 on 2024-02-19 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuildNestApp', '0006_constructionsite_site_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='site_id',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='user',
        ),
        migrations.DeleteModel(
            name='ConstructionSite',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
