# Generated by Django 5.0.1 on 2024-02-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuildNestApp', '0008_constructionsite_worker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
