# Generated by Django 5.0.1 on 2024-02-19 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildNestApp', '0009_delete_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job_role', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('salary_frequency', models.CharField(max_length=10)),
                ('salary_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuildNestApp.constructionsite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
