# Generated by Django 5.0.1 on 2024-02-19 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuildNestApp', '0010_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='salary_amount',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='salary_frequency',
        ),
    ]
