# Generated by Django 5.0.1 on 2024-02-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildNestApp', '0011_remove_worker_salary_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='salary_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='salary_frequency',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
