# Generated by Django 5.0.1 on 2024-02-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildNestApp', '0012_worker_salary_amount_worker_salary_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job_role', models.CharField(max_length=50)),
                ('plumber_main', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(max_length=20)),
            ],
        ),
    ]
