# Generated by Django 5.0.1 on 2024-02-22 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuildNestApp', '0013_mainworker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainWorker',
        ),
    ]
