# Generated by Django 5.0.1 on 2024-02-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildNestApp', '0014_delete_mainworker'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='aadhar_document',
            field=models.FileField(blank=True, null=True, upload_to='aadhar_documents/'),
        ),
    ]
