# Generated by Django 5.0.1 on 2024-02-29 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuildNestApp', '0015_worker_aadhar_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='site_id',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='user',
        ),
    ]
