# Generated by Django 5.0.1 on 2024-02-29 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuildNestApp', '0016_remove_worker_site_id_remove_worker_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
