# Generated by Django 5.0.1 on 2024-02-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildNestApp', '0017_delete_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job_role', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('salary_frequency', models.CharField(max_length=10, null=True)),
                ('salary_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('aadhar_document', models.FileField(blank=True, null=True, upload_to='aadhar_documents/')),
            ],
        ),
    ]
