# Generated by Django 5.0.1 on 2024-02-29 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuildNestApp', '0018_worker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
