# Generated by Django 5.0.1 on 2024-03-04 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuildNestApp', '0023_material'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
    ]
