# Generated by Django 5.0.1 on 2024-03-05 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuildNestApp', '0025_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
