# Generated by Django 5.0.1 on 2024-03-07 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuildNestApp', '0031_cartitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructionsite',
            name='user',
        ),
    ]
