# Generated by Django 5.0.1 on 2024-03-07 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuildNestApp', '0032_remove_constructionsite_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='site',
        ),
        migrations.DeleteModel(
            name='ConstructionSite',
        ),
    ]
