# Generated by Django 5.0.1 on 2024-03-07 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuildNestApp', '0034_constructionsite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
