# Generated by Django 5.0.1 on 2024-03-07 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildNestApp', '0036_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionSiteAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construction_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuildNestApp.constructionsite')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuildNestApp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
